# Generated by Django 5.2.4 on 2025-07-30 02:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('full_date', models.DateField()),
                ('year', models.IntegerField()),
                ('month', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('is_sended', models.BooleanField(default=False)),
                ('is_readed', models.BooleanField(default=False)),
                ('is_signed', models.BooleanField(default=False)),
                ('sended_date', models.DateTimeField(blank=True, null=True)),
                ('readed_date', models.DateTimeField(blank=True, null=True)),
                ('signed_date', models.DateTimeField(blank=True, null=True)),
                ('employee_full_name', models.CharField(max_length=255)),
                ('employee_number', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
